### ISSUE TITLE
Error when I delete and enter data quickly with backspace and enter keys

### ISSUE THREAD

**Issue by iBuitron** [plotly/dash-ag-grid#223]
I'm making a grids from a inputs in another gird. (image below)

Just for test, i input values and it generate others grids, works as i espect.
also, when i delete those values, the generated grid also delete.

but, when i do it fast (input values  with enter and then deleted with backspace) it gives me an error:

```
An object was provided as `children` instead of a component, string, or number (or list of those). Check the children property that looks something like:
{
  "props": {
    "columnState": []
  }
}
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
Error: An object was provided as `children` instead of a component, string, or number (or list of those). Check the children property that looks something like:

{

  "props": {

    "columnState": []

  }

}

    at validateComponent (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:2986:11)

    at BaseTreeContainer.getComponent (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:3624:79)

    at BaseTreeContainer.render (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:3800:19)

    at finishClassComponent (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:17295:33)

    at updateClassComponent (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:17245:26)

    at beginWork (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:18755:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:23338:9)
```

```
Cannot read properties of undefined (reading 'type')
15:06:57
Cannot read properties of undefined (reading 'type')
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read properties of undefined (reading 'type')

    at Object.resolve (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:9030:26)

    at BaseTreeContainer.getComponent (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:3625:71)

    at BaseTreeContainer.render (http://127.0.0.1:5000/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_11_1m1689267958.dev.js:3800:19)

    at finishClassComponent (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:17295:33)

    at updateClassComponent (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:17245:26)

    at beginWork (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:18755:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:5000/_dash-component-suites/dash/deps/react-dom@16.v2_11_1m1689267958.14.0.js:23338:9)
```

![image](https://github.com/plotly/dash-ag-grid/assets/102157308/ba7f0af4-f2b9-4ac7-ad12-706792c02a07)

From the image, the first grid has a "x" value, that makes me a new grid. 
I can't share the code cuz is part of my project, but if someone from the staff wants to see what happens, we can do a meet.

**Comment by BSd3v** [comment]
It sounds like you are in the middle of a callback when it removes the grid.

If possible, maybe hide the grid first and then delete it?

It would be nice to actually see the code behind how this is working to be able to diagnose this a bit more.

**Comment by dragonite00** [comment]
get the same issue in #233 , when ag-grids leave the space I think there's some lingering js callbacks that crash the app

**Comment by BSd3v** [comment]
Hello @dragonite00/ @iBuitron,

Can you test your issues on v31, we just released this yesterday. Since neither of you provided full working examples, its hard to test your exact use-cases.

**Comment by BSd3v** [comment]
closing this as stale, reopen if the issue persists
