### ISSUE TITLE
Does comparator work when defining table columns?

### ISSUE THREAD

**Issue by mburger-stsci** [plotly/dash-ag-grid#52]
I'm trying to write a custom sort function for a table column. Here's what I have:

```
    def make_author_table(self):
        def author_sort(valueA, valueB, nodeA=None, nodeB=None,
                        isDescending=True):
            sortA = self.authors.loc[self.authors.fullname == valueA,
                                     'sortname'].values[0]
            sortB = self.authors.loc[self.authors.fullname == valueB,
                                     'sortname'].values[0]
            if sortA > sortB:
                return 1
            elif sortA < sortB:
                return -1
            else:
                return 0
    
        authors = self.authors[['fullname', 'gender', 'nationality',
                                'demographic']].copy()
        authors.columns = ['Name', 'Gender', 'Nationality', 'Demographic']
        columnDefs = [{'field': 'Name', 'editable': True,
                       'comparator': author_sort},
                      {'field': 'Gender', 'editable': True},
                      {'field': 'Nationality', 'editable': True},
                      {'field': 'Demographic', 'editable': True}]
        author_table = dag.AgGrid(
            id='authors',
            className='ag-theme-alpine',
            columnDefs=columnDefs,
            rowData=authors.to_dict("records"),
            columnSize="sizeToFit",
            defaultColDef={"resizable":True, "sortable":True, "filter":True},
            dashGridOptions={"undoRedoCellEditing":True, "rowSelection":"single"})
        return author_table
```

This is the error I get:
```
Traceback (most recent call last):
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_callback.py", line 480, in add_context
    jsonResponse = to_json(response)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_utils.py", line 22, in to_json
    return to_json_plotly(value)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/plotly/io/_json.py", line 123, in to_json_plotly
    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)
  File "/Users/mburger/anaconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/_plotly_utils/utils.py", line 59, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "/Users/mburger/anaconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/mburger/anaconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/_plotly_utils/utils.py", line 136, in default
    return _json.JSONEncoder.default(self, obj)
  File "/Users/mburger/anaconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/dash.py", line 1273, in dispatch
    ctx.run(
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_callback.py", line 482, in add_context
    _validate.fail_callback_output(output_value, output)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_validate.py", line 326, in fail_callback_output
    _validate_value(val, index=i)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_validate.py", line 302, in _validate_value
    _raise_invalid(bad_val=j, outer_val=val, path=p, index=index)
  File "/Users/mburger/anaconda3/lib/python3.9/site-packages/dash/_validate.py", line 230, in _raise_invalid
    raise exceptions.InvalidCallbackReturnValue(
dash.exceptions.InvalidCallbackReturnValue: The callback for `<Output `tab_content.children`>`
                returned a tree with one value having type `AgGrid`
                which is not JSON serializable.


The value in question is located at
[0] Div 
[0] AgGrid (id=authors),

   <snip>

                In general, Dash properties can only be
                dash components, strings, dictionaries, numbers, None,
                or lists of those.
```
I can't find a python example for "comparator", so I'm not sure if I've done this wrong, if it's a bug, or just a feature that hasn't been implemented.

**Comment by AnnMarieW** [comment]
Hi @mburger-stsci 
We haven't enabled allowing functions to be passed to the comparator prop yet.  Should be in the next release :slightly_smiling_face:

**Comment by mburger-stsci** [comment]
Great. Thank you for responding. I'll keep an eye out for the next release.

**Comment by BSd3v** [comment]
Hello @mburger-stsci,

The a3 version should have this working now.

You need to define the comparator function on the JS side, and not python.

There are quite a few examples of how to use these functions in the documents: https://dashaggrid.pythonanywhere.com/rendering/value-formatters-custom-functions

Could you please confirm that you are able to get this performing? 😄

**Comment by BSd3v** [comment]
@mburger-stsci,

Can you give some test data and tell a little bit of how you want the the filter to work?

**Comment by Thuener** [comment]
I want to use comparator to sort row for a column that I'm using Markdown.

For what I undestand I should create a function on the

**Comment by AnnMarieW** [comment]
@Thuener  Thanks for reporting - and good detective work :detective:

**Comment by BSd3v** [comment]
@Thuener,

Do you have an example of the code and comparator you were trying to use?

**Comment by BSd3v** [comment]
Here is an example of this working:

```
"""
Custom Comparator
"""

import dash_ag_grid as dag
from dash import Dash, html, dcc
import pandas as pd

app = Dash(__name__)


df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

# basic columns definition with column defaults
columnDefs= [
        { "field": 'athlete', "sort": 'desc' },
        { "field": 'age', "width": 90 },
        { "field": 'country' },
        { "field": 'year', "width": 90, "unSortIcon": True },
        { "field": 'date', "comparator": {"function": "dateComparator"} },
        { "field": 'sport' },
        { "field": 'gold' },
        { "field": 'silver' },
        { "field": 'bronze' },
        { "field": 'total' },
      ]
defaultColDef= {
"width": 170,
"sortable": True,
}

app.layout = html.Div(
    [
        dcc.Markdown("Date Sort Comparator Example"),
        dag.AgGrid(columnDefs=columnDefs, rowData=df.to_dict("records"), defaultColDef=defaultColDef),
    ],
    style={"margin": 20},
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

js file:
```
dagfuncs.dateComparator = function (date1, date2) {
  const date1Number = monthToComparableNumber(date1);
  const date2Number = monthToComparableNumber(date2);
  if (date1Number === null && date2Number === null) {
    return 0;
  }
  if (date1Number === null) {
    return -1;
  }
  if (date2Number === null) {
    return 1;
  }
  return date1Number - date2Number;
}

// eg 29/08/2004 gets converted to 20040829
function monthToComparableNumber(date) {
  if (date === undefined || date === null || date.length !== 10) {
    return null;
  }
  const yearNumber = Number.parseInt(date.substring(6, 10));
  const monthNumber = Number.parseInt(date.substring(3, 5));
  const dayNumber = Number.parseInt(date.substring(0, 2));
  return yearNumber * 10000 + monthNumber * 100 + dayNumber;
}
```

This wont be available til the next release
```
